import "./globals.css";
import { Inter } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';
import { Suspense } from "react";
import Loading from "./loading";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body
          className={`${inter.className} bg-neutral-900 min-h-screen font-Roboto text-neutral-200`}
        >
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
          <Analytics />
        </body>
      </html>
  );
}
